@tool
class_name DialogueParser
extends RefCounted

## Parses .dlg source text into a [DialogueResource].
##
## Supports two authoring formats:
##
## - [b]Story Mode[/b] (default for new files) — speaker-driven, no node IDs:
## [codeblock]
## NPC: Blacksmith
##
## Blacksmith:
## Need a blade sharpened?
##
## Player:
## Show me your wares.
## => Open Shop
##
## Scene: Open Shop
## Blacksmith:
## Take a look.
## do: open_shop blacksmith_inventory
## [/codeblock]
##
## - [b]Structured Mode[/b] — explicit node IDs and directives, for engineers
## or files generated by tooling:
## [codeblock]
## NPC: blacksmith
## START: greeting
##
## [greeting]
## NPC: Need a blade sharpened?
## CHOICE: Show me your wares -> shop
##
## [shop]
## NPC: Take a look.
## EFFECT: open_shop blacksmith_inventory
## [/codeblock]
##
## Auto-detection: a file is parsed as structured mode if any line is a bare
## `[identifier]` node header, otherwise as story mode.

## Parse result returned by [method parse].
class ParseResult:
	var resource: DialogueResource
	var errors: Array[Dictionary] = []  # [{line: int, message: String}]

	func ok() -> bool:
		return errors.is_empty()


# Reserved words that cannot be used as story-mode speaker names. Compared
# case-insensitively. `NPC` is reserved at the file head but allowed as a
# speaker name once content has started; handled in `_parse_story`.
const _RESERVED_SPEAKERS := ["scene", "if", "do", "vo", "subtitle", "loc",
		"playback", "speaker", "end", "start", "choice", "condition", "effect",
		"choice_if", "choice_do", "vo_event", "vo_audio"]


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------

## Parses [param source_text] and returns a [ParseResult]. Auto-detects format.
static func parse(source_text: String, source_id: String = "") -> ParseResult:
	if _has_structured_markers(source_text):
		return _parse_structured(source_text, source_id)
	return _parse_story(source_text, source_id)


# Returns true if any non-empty line is a bare `[identifier]` node header,
# which is the signal that this file is in structured mode.
static func _has_structured_markers(text: String) -> bool:
	var lines := text.split("\n", false)
	for raw in lines:
		var line := raw.strip_edges()
		if line.length() < 3:
			continue
		if line.begins_with("[") and line.ends_with("]"):
			# Quick sanity: the content between brackets should be id-shaped.
			var inner := line.substr(1, line.length() - 2).strip_edges()
			if not inner.is_empty():
				return true
	return false


# ---------------------------------------------------------------------------
# Structured mode (the original format, plus CHOICE_IF / CHOICE_DO)
# ---------------------------------------------------------------------------

static func _parse_structured(source_text: String, source_id: String) -> ParseResult:
	var result := ParseResult.new()
	result.resource = DialogueResource.new()
	result.resource.dialogue_id = source_id

	var lines := source_text.split("\n", true)
	var current_node: DialogueNodeResource = null
	var seen_node_ids := {}

	# Per-choice condition/effect buffers. Accumulate when CHOICE_IF: /
	# CHOICE_DO: lines are seen; consumed by the next CHOICE: line.
	var pending_choice_conditions: Array[DialogueCondition] = []
	var pending_choice_effects: Array[DialogueEffect] = []

	for i in lines.size():
		var line_num := i + 1
		var raw := lines[i]
		var line := raw.strip_edges()

		if line.is_empty() or line.begins_with("#"):
			continue

		# --- Node header: [node_id] ---
		if line.begins_with("[") and line.ends_with("]"):
			var node_id := line.substr(1, line.length() - 2).strip_edges()
			if node_id.is_empty():
				_add_error(result, line_num, "Empty node id in '[]' header")
				continue
			if seen_node_ids.has(node_id):
				_add_error(result, line_num, "Duplicate node id '%s' (also defined earlier)" % node_id)
			seen_node_ids[node_id] = true

			current_node = DialogueNodeResource.new()
			current_node.node_id = node_id
			current_node.speaker = result.resource.npc_id
			result.resource.nodes[node_id] = current_node
			_clear_pending(pending_choice_conditions, pending_choice_effects)
			continue

		# --- Directive lines (KEYWORD: value) ---
		var colon_idx := line.find(":")
		if colon_idx < 0:
			if line == "END":
				if current_node == null:
					_add_error(result, line_num, "'END' outside of any node")
				else:
					current_node.is_end = true
				continue
			_add_error(result, line_num, "Unrecognized line: '%s'" % line)
			continue

		var keyword := line.substr(0, colon_idx).strip_edges().to_upper()
		var value := line.substr(colon_idx + 1).strip_edges()

		match keyword:
			"NPC":
				if current_node == null:
					if not result.resource.npc_id.is_empty():
						_add_error(result, line_num, "Duplicate file-level 'NPC:' declaration")
					result.resource.npc_id = value
				else:
					if not current_node.text.is_empty():
						_add_error(result, line_num, "Node '%s' already has dialogue text" % current_node.node_id)
					current_node.text = value
					if current_node.speaker.is_empty():
						current_node.speaker = result.resource.npc_id

			"START":
				if current_node != null:
					_add_error(result, line_num, "'START:' must appear before any node")
				if not result.resource.start_node_id.is_empty():
					_add_error(result, line_num, "Duplicate 'START:' declaration")
				result.resource.start_node_id = value

			"CHOICE":
				if current_node == null:
					_add_error(result, line_num, "'CHOICE:' outside of any node")
					continue
				var choice := _parse_choice(value, line_num, result)
				if choice != null:
					# Attach any pending per-choice conditions/effects.
					for c in pending_choice_conditions:
						choice.conditions.append(c)
					for e in pending_choice_effects:
						choice.effects.append(e)
					current_node.choices.append(choice)
				_clear_pending(pending_choice_conditions, pending_choice_effects)

			"CHOICE_IF":
				var c := _parse_condition(value, line_num, result)
				if c != null:
					pending_choice_conditions.append(c)

			"CHOICE_DO":
				var e := _parse_effect(value, line_num, result)
				if e != null:
					pending_choice_effects.append(e)

			"EFFECT":
				if current_node == null:
					_add_error(result, line_num, "'EFFECT:' outside of any node")
					continue
				var effect := _parse_effect(value, line_num, result)
				if effect != null:
					current_node.effects.append(effect)

			"CONDITION":
				if current_node == null:
					_add_error(result, line_num, "'CONDITION:' outside of any node")
					continue
				var condition := _parse_condition(value, line_num, result)
				if condition != null:
					current_node.conditions.append(condition)

			"VO_EVENT":
				if current_node == null:
					_add_error(result, line_num, "'VO_EVENT:' outside of any node")
					continue
				current_node.voiceover_event_id = value

			"VO_AUDIO":
				if current_node == null:
					_add_error(result, line_num, "'VO_AUDIO:' outside of any node")
					continue
				current_node.voiceover_audio_path = value

			"SUBTITLE":
				if current_node == null:
					_add_error(result, line_num, "'SUBTITLE:' outside of any node")
					continue
				current_node.subtitle_text_key = value

			"SPEAKER":
				if current_node == null:
					_add_error(result, line_num, "'SPEAKER:' outside of any node")
					continue
				current_node.speaker = value

			"PLAYBACK":
				if current_node == null:
					_add_error(result, line_num, "'PLAYBACK:' outside of any node")
					continue
				current_node.playback_behavior = value

			"LOCALIZATION", "LOC":
				if current_node == null:
					_add_error(result, line_num, "'%s:' outside of any node" % keyword)
					continue
				current_node.localization_key = value

			_:
				_add_error(result, line_num, "Unknown keyword '%s'" % keyword)

	# Warn if there are unconsumed per-choice directives at end of file.
	if not pending_choice_conditions.is_empty() or not pending_choice_effects.is_empty():
		_add_error(result, lines.size(),
				"CHOICE_IF: / CHOICE_DO: at end of file with no following CHOICE:")

	return result


# ---------------------------------------------------------------------------
# Story mode
# ---------------------------------------------------------------------------

static func _parse_story(source_text: String, source_id: String) -> ParseResult:
	var result := ParseResult.new()
	result.resource = DialogueResource.new()
	result.resource.dialogue_id = source_id

	var lines := source_text.split("\n", true)

	# Parser state
	var current_node: DialogueNodeResource = null
	var current_block_speaker: String = ""           # "" = no active block
	var current_block_text: Array[String] = []
	var current_choice: DialogueChoiceResource = null
	var seen_node_ids := {}
	var header_finalized := false                   # true once content has started

	for i in lines.size():
		var line_num := i + 1
		var raw := lines[i]
		var line := raw.strip_edges()

		if line.begins_with("#"):
			continue

		# --- File-level header: NPC: <id> appears before any content ---
		# (Detected by being NPC:-prefixed AND no content has started yet.)
		if not header_finalized and line.begins_with("NPC:") and current_node == null and current_block_speaker.is_empty():
			# Only treat as header if the rest of the line is a single id-shaped token
			# OR if we haven't seen content yet at all. Be permissive — most files
			# put `NPC: <name>` right at the top.
			if not result.resource.npc_id.is_empty():
				_add_error(result, line_num, "Duplicate file-level 'NPC:' declaration")
			result.resource.npc_id = line.substr(4).strip_edges()
			continue

		# --- Scene: <Name> ---
		if line.begins_with("Scene:") or line.begins_with("scene:") or line.begins_with("SCENE:"):
			_flush_story_block(current_node, current_choice, current_block_speaker, current_block_text)
			current_block_speaker = ""
			current_block_text.clear()
			current_choice = null

			var scene_name := line.substr(6).strip_edges()
			if scene_name.is_empty():
				_add_error(result, line_num, "'Scene:' with no name")
				continue
			var scene_id := _slugify(scene_name)
			if seen_node_ids.has(scene_id):
				_add_error(result, line_num, "Scene '%s' duplicates an earlier scene (both slug to '%s')" % [scene_name, scene_id])
			seen_node_ids[scene_id] = true

			current_node = DialogueNodeResource.new()
			current_node.node_id = scene_id
			current_node.speaker = result.resource.npc_id
			result.resource.nodes[scene_id] = current_node
			if result.resource.start_node_id.is_empty():
				result.resource.start_node_id = scene_id
			header_finalized = true
			continue

		# --- => <Target> ---
		if line.begins_with("=>"):
			var target_name := line.substr(2).strip_edges()
			if target_name.is_empty():
				_add_error(result, line_num, "'=>' with no target")
				continue
			var target_id := _slugify(target_name)

			if current_choice != null:
				if not current_choice.target_node_id.is_empty():
					_add_error(result, line_num, "Choice already has a '=>' target")
				current_choice.target_node_id = target_id
			elif current_block_speaker != "" and current_node != null:
				# Auto-advance: bare `=>` after an NPC block. Model as an
				# unnamed choice that the UI / playback_behavior treats as
				# a "Continue" prompt.
				var continue_choice := DialogueChoiceResource.new()
				continue_choice.text = ""
				continue_choice.target_node_id = target_id
				current_node.choices.append(continue_choice)
			else:
				_add_error(result, line_num, "'=>' outside of any speaker block")
			continue

		# --- if: <condition> ---
		if line.begins_with("if:"):
			var cond := _parse_condition(line.substr(3).strip_edges(), line_num, result)
			if cond != null:
				if current_choice != null:
					current_choice.conditions.append(cond)
				elif current_node != null:
					current_node.conditions.append(cond)
				else:
					_add_error(result, line_num, "'if:' outside of any node")
			continue

		# --- do: <effect> ---
		if line.begins_with("do:"):
			var eff := _parse_effect(line.substr(3).strip_edges(), line_num, result)
			if eff != null:
				if current_choice != null:
					current_choice.effects.append(eff)
				elif current_node != null:
					current_node.effects.append(eff)
				else:
					_add_error(result, line_num, "'do:' outside of any node")
			continue

		# --- vo: <event_id> ---
		if line.begins_with("vo:"):
			if current_node == null:
				_add_error(result, line_num, "'vo:' outside of any node")
				continue
			current_node.voiceover_event_id = line.substr(3).strip_edges()
			continue

		# --- subtitle: <key> ---
		if line.begins_with("subtitle:"):
			if current_node == null:
				_add_error(result, line_num, "'subtitle:' outside of any node")
				continue
			current_node.subtitle_text_key = line.substr(9).strip_edges()
			continue

		# --- playback: <mode> ---
		if line.begins_with("playback:"):
			if current_node == null:
				_add_error(result, line_num, "'playback:' outside of any node")
				continue
			current_node.playback_behavior = line.substr(9).strip_edges()
			continue

		# --- <Speaker>: [inline text] ---
		var speaker := _match_speaker_header(line)
		if speaker != "":
			# End previous block.
			_flush_story_block(current_node, current_choice, current_block_speaker, current_block_text)
			current_block_speaker = speaker
			current_block_text.clear()
			current_choice = null

			# Ensure we have a node to attach to. Implicit "start" scene if none.
			if current_node == null:
				current_node = _create_implicit_start(result, seen_node_ids)
			header_finalized = true

			# Player speakers become choices on the current node.
			if speaker.to_lower() == "player":
				current_choice = DialogueChoiceResource.new()
				current_node.choices.append(current_choice)

			# Inline text on same line as the speaker header.
			var colon_idx := line.find(":")
			var inline := line.substr(colon_idx + 1).strip_edges()
			if not inline.is_empty():
				current_block_text.append(inline)
			continue

		# --- Default: text content (within an active speaker block) ---
		if current_block_speaker.is_empty():
			if not line.is_empty():
				_add_error(result, line_num, "Text outside of any speaker block: '%s'" % line)
			continue

		# Preserve the line — including blank lines for paragraph breaks. Use
		# the stripped form so leading/trailing spaces don't sneak in.
		current_block_text.append(line)

	# Flush the final block at EOF.
	_flush_story_block(current_node, current_choice, current_block_speaker, current_block_text)
	return result


# Trim trailing blank lines from a story-mode text buffer and write the
# result to the current choice (if Player block) or current node (if NPC block).
static func _flush_story_block(
		current_node: DialogueNodeResource,
		current_choice: DialogueChoiceResource,
		speaker: String,
		buffer: Array[String]) -> void:
	if speaker.is_empty():
		return
	# Trim trailing blank lines.
	while buffer.size() > 0 and buffer[buffer.size() - 1].is_empty():
		buffer.pop_back()
	if buffer.is_empty():
		return
	var text := "\n".join(buffer)
	if current_choice != null:
		current_choice.text = text
	elif current_node != null:
		current_node.text = text
		if speaker.to_lower() != "npc":
			current_node.speaker = speaker


# Returns the speaker name if [param line] is a story-mode speaker header
# (e.g. "Blacksmith:" or "Captain Aldric: Hello there"), or "" otherwise.
static func _match_speaker_header(line: String) -> String:
	var colon_idx := line.find(":")
	if colon_idx <= 0:
		return ""
	var prefix := line.substr(0, colon_idx).strip_edges()
	if prefix.is_empty() or prefix.length() > 64:
		return ""
	# Speaker names are short proper-noun-shaped tokens: letters, digits,
	# spaces, apostrophes, hyphens, periods. Allows "Captain Aldric",
	# "R2-D2", "Mr. Smith", "Player 1", and so on.
	for j in prefix.length():
		var ch := prefix[j]
		var code := ch.unicode_at(0)
		var is_alpha := (code >= 0x41 and code <= 0x5A) or (code >= 0x61 and code <= 0x7A)
		var is_digit := code >= 0x30 and code <= 0x39
		var is_space := ch == " "
		var is_punct := ch == "'" or ch == "-" or ch == "."
		if not (is_alpha or is_digit or is_space or is_punct):
			return ""
	# Reserved keywords are never speaker names.
	if prefix.to_lower() in _RESERVED_SPEAKERS:
		return ""
	return prefix


# Build an implicit "start" scene when story-mode content begins without an
# explicit `Scene:` declaration. Idempotent if called repeatedly (returns the
# existing implicit start).
static func _create_implicit_start(result: ParseResult, seen_node_ids: Dictionary) -> DialogueNodeResource:
	var id := "start"
	if seen_node_ids.has(id):
		return result.resource.nodes[id]
	var node := DialogueNodeResource.new()
	node.node_id = id
	node.speaker = result.resource.npc_id
	result.resource.nodes[id] = node
	seen_node_ids[id] = true
	if result.resource.start_node_id.is_empty():
		result.resource.start_node_id = id
	return node


# Slugify a scene name to a node_id. "Quest Offer" → "quest_offer".
static func _slugify(s: String) -> String:
	var lower := s.to_lower().strip_edges()
	var out := ""
	var prev_sep := true  # prevents leading underscore
	for i in lower.length():
		var ch := lower[i]
		var code := ch.unicode_at(0)
		var is_alnum := (code >= 0x61 and code <= 0x7A) or (code >= 0x30 and code <= 0x39)
		if is_alnum:
			out += ch
			prev_sep = false
		elif not prev_sep:
			out += "_"
			prev_sep = true
	while out.ends_with("_"):
		out = out.substr(0, out.length() - 1)
	if out.is_empty():
		return "scene"
	return out


static func _clear_pending(
		conditions: Array[DialogueCondition],
		effects: Array[DialogueEffect]) -> void:
	conditions.clear()
	effects.clear()


# ---------------------------------------------------------------------------
# Shared sub-parsers
# ---------------------------------------------------------------------------

# Choice: "text -> target" or "text" (terminal)
static func _parse_choice(value: String, line_num: int, result: ParseResult) -> DialogueChoiceResource:
	var choice := DialogueChoiceResource.new()
	var arrow_idx := value.find("->")
	if arrow_idx < 0:
		choice.text = value
		return choice
	choice.text = value.substr(0, arrow_idx).strip_edges()
	choice.target_node_id = value.substr(arrow_idx + 2).strip_edges()
	if choice.text.is_empty():
		_add_error(result, line_num, "Empty choice text")
		return null
	return choice


# Effect: "kind arg1 arg2 ..."
static func _parse_effect(value: String, line_num: int, result: ParseResult) -> DialogueEffect:
	var tokens := value.split(" ", false)
	if tokens.is_empty():
		_add_error(result, line_num, "Empty effect")
		return null
	var effect := DialogueEffect.new()
	effect.kind = tokens[0]
	for j in range(1, tokens.size()):
		effect.args.append(tokens[j])
	return effect


# Condition: "[!]kind arg1 arg2 ..."
static func _parse_condition(value: String, line_num: int, result: ParseResult) -> DialogueCondition:
	var negated := false
	if value.begins_with("!"):
		negated = true
		value = value.substr(1).strip_edges()
	var tokens := value.split(" ", false)
	if tokens.is_empty():
		_add_error(result, line_num, "Empty condition")
		return null
	var condition := DialogueCondition.new()
	condition.kind = tokens[0]
	condition.negated = negated
	for j in range(1, tokens.size()):
		condition.args.append(tokens[j])
	return condition


static func _add_error(result: ParseResult, line: int, message: String) -> void:
	result.errors.append({"line": line, "message": message})
